---
title: "IPEDS Peer Data Analysis"
subtitle: "The Company We Keep"
author: "Jason P. Casey"
output: html_notebook
date: 2019-05-07
params:
  node:
    label: "Focus Node"
    value: 181464
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(fig.width = 8,
                      fig.asp = 0.618,
                      echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

# Additional libraries
library(odbc)
library(igraph)
library(readxl)
library(reticulate)
library(tidyverse)
library(plotly)
library(htmlwidgets)
library(networkD3)

set.seed(1965)

```

# Load Data

## Institution File

Both institution and peer files originated from https://nces.ed.gov/ipeds.

```{r}
institutions <- read_excel("data/HD2016.xlsx") %>%
  rename_all(tolower) %>%
  select(unitid, institution_name = instnm, state = stabbr, control, list_type = dfrcuscg)

institutions
```

## Peer File

```{r}
big_10 <- tribble(
  ~peer_unitid,
  153658, 
  163286, 
  170976, 
  171100, 
  174066, 
  181464, 
  186380, 
  204796, 
  214777, 
  240444, 
  243780, 
  145637, 
  151351, 
  147767
)

regents <- tribble(
  ~peer_unitid,
  153603, 
  153658, 
  155317, 
  174066, 
  178396, 
  181464, 
  204796, 
  243780, 
  126614, 
  126818, 
  145637
)

big_10 <- big_10 %>%
  mutate(unitid = 181464)

peers <- read_excel("data/CUSTOMCGIDS2016.xlsx") %>%
  rename_all(tolower) %>%
  select(unitid, peer_unitid = cgunitid) %>%
  bind_rows(big_10) %>%
  distinct(unitid, peer_unitid)

peers
```

# What Peers Do We Follow?

```{r}
unl_peers <- peers %>%
  filter(unitid==181464) %>%
  inner_join(institutions, by=c('peer_unitid' = 'unitid')) %>%
  mutate(unitid = peer_unitid) %>%
  select(unitid, institution_name, state)

unl_peers

```

# Institutions That Consider UNL a Peer

```{r}
unl_monitors <- peers %>%
  filter(peer_unitid==181464) %>%
  count(unitid) %>%
  inner_join(institutions) %>%
  select(unitid, institution_name, state)

unl_monitors
```

# Mututal Peers

```{r}
mutual <- unl_monitors %>%
  intersect(unl_peers)

mutual
```

```{r include=FALSE}
base_group <- institutions %>%
  filter(unitid==181464) %>%
  select(unitid, institution_name, state) %>%
  union(unl_monitors) %>%
  union(unl_peers) %>%
  select(unitid, institution_name, state)

ids <- base_group %>%
  select(unitid)

net_nodes <- peers %>%
  inner_join(ids) %>%
  inner_join(institutions, by=c('peer_unitid' = 'unitid')) %>%
  mutate(unitid = peer_unitid) %>%
  select(unitid, institution_name, state) %>%
  union(base_group) %>%
  mutate(peer_list = 5,
         peer_list = ifelse(unitid %in% unl_monitors$unitid, 4, peer_list),
         peer_list = ifelse(unitid %in% unl_peers$unitid, 3, peer_list),
         peer_list = ifelse(unitid %in% mutual$unitid, 2, peer_list),
         peer_list = ifelse(unitid == 181464, 1, peer_list))

net_edges <- ids %>%
  inner_join(peers)

# create edges and nodes for the graph
edges <- net_edges
nodes <- net_nodes

# create igraph object from nodes and edges
g <- graph_from_data_frame(d=edges, vertices=nodes, directed=TRUE)

# Set edge names to institution names rather than unitid's
V(g)$label <- V(g)$institution_name
V(g)$group <- V(g)$peer_list
V(g)[V(g)$color==c("#cc0000", "#ff6666", "#ffcccc", "#737373", "#e6e6e6")[V(g)$group]]
#plot the network
# l <- layout_with_kk(g)
l <- layout_with_fr(g)
```


```{r pressure, echo=FALSE}
plot(g, edge.arrow.size=.2,
     vertex.size=5,
     vertex.label.cex=.25,
     vertex.label='',
     vertex.color=c("#cc0000", "#ff6666", "#ffcccc", "#737373", "#e6e6e6")[V(g)$group],
     layout=l)

```

# Plotly Example

```{r}
vs <- V(g)
vs$color <- 
es <- as.data.frame(get.edgelist(g))
es <- as_tibble(es)

Nv <- length(vs)
Ne <- length(es[1]$V1)

```

```{r}
Xn <- l[,1]
Yn <- l[,2]

network <- plot_ly(x = ~Xn, y = ~Yn,
                   mode = "markers",
                   text = vs$label,
                   color = list("#E6E6E6"),
                   hoverinfo = "text")
```

```{r}
edge_shapes <- list()
for(i in 1:Ne) {
  v0 <- es[i,]$V1
  v1 <- es[i,]$V2

  edge_shape = list(
    type = "line",
    line = list(color = "#E6E6E6", width = 0.3),
    x0 = Xn[v0],
    y0 = Yn[v0],
    x1 = Xn[v1],
    y1 = Yn[v1]
  )

  edge_shapes[[i]] <- edge_shape
}
```

```{r}
axis <- list(title = "", showgrid = FALSE, showticklabels = FALSE, zeroline = FALSE)

p <- layout(
  network,
  title = 'Peer Network',
  shapes = edge_shapes,
  xaxis = axis,
  yaxis = axis
)

# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
# chart_link = api_create(p, filename="peer-network-r")
# chart_link
p
```

# networkD3 From igraph

```{r}
peer_net_D3 <- igraph_to_networkD3(g)
peer_net_D3$nodes$group = as.character(V(g)$group)
peer_net_D3$nodes$label = V(g)$label

ColourScale <- 'd3.scaleOrdinal()
            .domain(["1", "2", "3", "4", "5"])
           .range(["#D00000","#FF6666","#FFCCCC", "#737373", "#A3BACB"]);'
           
forceNetwork(Links = peer_net_D3$links,
             Nodes = peer_net_D3$nodes,
             Source = 'source',
             Target = 'target',
             NodeID = 'label',
             Group = 'group',
             linkColour = "#E6E6E6",
             fontFamily = "sans-serif",
             fontSize = 14,
             colourScale = JS(ColourScale),
             opacity = 1.0)
```

# networkD3 From Data

```{r}
# MisNodes
peer_net_D3$nodes
```

```{r}
MisLinks
```

```{r}
net_nodes <-
  net_nodes %>%
  rename(name = institution_name,
         group = peer_list) %>%
  mutate(size = 10) %>%
  as.data.frame()
```

```{r}
net_edges <-
  net_edges %>%
  rename(source = unitid, target = peer_unitid) %>%
  mutate(value = 1) %>%
  as.data.frame()
```

```{r}
forceNetwork(Links = net_edges,
             Nodes = net_nodes,
             Source = "source",
             Target = "target",
             Value = "value",
             NodeID = "name",
             Group = "group",
             opacity = 1.0)
```



