---
title: "R Notebook"
output: html_notebook
---

# Setup and Opend Database Connection

```{r}
rm(list=ls())

# Load needed libraries
library(VennDiagram)
library(odbc)
library(igraph)
library(stringr)
library(tidyverse)

# set global variables
odbcString <- "ipeds"

# set this for reproducibility of results
set.seed(1001)

grabData <- function(dbString, queryString)
{
  # Open a connection
  connection <- dbConnect(odbc::odbc(), dbString)
  
  response <- dbSendQuery(connection, queryString)
  tbl <- dbFetch(response)
  dbClearResult(response)
  
  # disconnect from the database
  dbDisconnect(connection)

  return(as_tibble(tbl))
}

```

## Load Institutions Table

```{r}
qry <- 'SELECT i.UNITID AS Unitid,
               i.INSTNM AS InstitutionName,
               i.STABBR AS [State],
               i.CONTROL AS ControlCode,
               i.HLOFFER AS HighestLevelOffering
         FROM  dbo.HD2014 i'

insts <- grabData(odbcString, qry)

rm(qry)

insts

```

## Load Peers Table

```{r}
qry <- "SELECT c.UNITID AS Unitid, c.CGUNITID AS PeerUnitid FROM dbo.CUSTOMCGIDS2014 c"

peers <- grabData(odbcString, qry)

rm(qry)

peers

```

# Overlap Between Our Peers and Institutions that Moniror UNL

```{r}
grid.newpage()
draw.pairwise.venn(area1=10,
                   area2=25,
                   cross.area=3,
                   fontfamily = 'sans',
                   category=c('Peers', 'Monitors'),
                   fill = c("red", "light grey"),
                   alpha=rep(0.5, 2),
                   lty=rep('blank', 2),
                   rotation.degree = 45,
                   euler.d=TRUE)

```

# What Peers Do We Follow?

```{r}
unl.peers <- peers %>%
  filter(Unitid==181464) %>%
  inner_join(insts, by=c('PeerUnitid' = 'Unitid')) %>%
  mutate(Unitid = PeerUnitid) %>%
  select(Unitid, InstitutionName, State)

unl.peers

```

# Institutions That Consider UNL a Peer

```{r}
unl.monitors <- peers %>%
  filter(PeerUnitid==181464) %>%
  group_by(Unitid) %>%
  summarise(count=n()) %>%
  ungroup() %>%
  inner_join(insts) %>%
  select(Unitid, InstitutionName, State)

unl.monitors
```

# Mututal Peers

```{r}
mutual <- unl.monitors %>%
  intersect(unl.peers)

mutual
```

# Network

```{r}
unl <- insts %>%
  filter(Unitid==181464) %>%
  select(Unitid, InstitutionName, State)

base.group <- unl.monitors %>%
  union(unl.peers) %>%
  union(unl)

# create odes for the graph.  This is an unduplicated list of things that are related.
net.nodes <- peers %>%
  inner_join(base.group[,c('Unitid')]) %>%
  inner_join(insts, by=c('PeerUnitid' = 'Unitid')) %>%
  mutate(Unitid = PeerUnitid) %>%
  select(Unitid, InstitutionName, State) %>%
  union(base.group) %>%
  mutate(vgroup = 5,
         vgroup = ifelse(Unitid %in% unl.monitors$Unitid, 4, vgroup),
         vgroup = ifelse(Unitid %in% unl.peers$Unitid, 3, vgroup),
         vgroup = ifelse(Unitid %in% mutual$Unitid, 2, vgroup),
         vgroup = ifelse(Unitid == 181464, 1, vgroup))

# create edges for graph -- this contains the id pairs for each relatiohship.
net.edges <- base.group %>%
  select(Unitid) %>%
  inner_join(peers)

# create igraph object from nodes and edges
g <- graph_from_data_frame(d=net.edges, vertices=net.nodes, directed=TRUE)


l <- layout_with_kk(g)
# l <- layout_with_fr(g)

net.nodes
```


```{r}
# display the labels only for desired institutions
V(g)$label <- net.nodes$InstitutionName
V(g)$label[!net.nodes$vgroup < 4] <- NA

# set the vertex group to user-defined groups
V(g)$group <- net.nodes$vgroup

# set edge color based on group
E(g)$color <- '#e6e6e6'
E(g)[net.edges$Unitid==181464]$color <- 'black'

#plot the network
par(family='sans')
plot(g, edge.arrow.size=.2,
     vertex.size=5,
     vertex.label.cex=.65,
     vertex.color=c("#cc0000","#ff6666","#ffcccc","#737373","#e6e6e6")[V(g)$group],
     vertex.frame.color=c("#cc0000","#ff6666","#ffcccc","#737373","#e6e6e6")[V(g)$group],
     layout=l)
legend(x=-1.5, y=-0.9, pch=21,
       legend=c('UNL','Mutual Peer','Peer','Monitor','Other'),
       col=c("#cc0000","#ff6666","#ffcccc","#737373","#e6e6e6"),
       pt.bg=c("#cc0000","#ff6666","#ffcccc","#737373","#e6e6e6"))


```

